// AUTO-GENERATED by `npm run wiki:fetch`. Do not edit by hand.
//
// Output names of crafted intermediates (shared gifts / sub-gifts) whose direct
// ingredients match the GW2 wiki recipe in the committed snapshot. The detail
// tree badges nodes whose output.name is in this set as wiki-verified; anything
// absent renders as unverified and must be cross-checked. Regenerate after game
// updates with `npm run wiki:fetch`.
export const VERIFIED_INTERMEDIATES: ReadonlySet<string> = new Set([
  "Draconic Tribute",
  "Gift of Blood",
  "Gift of Bones",
  "Gift of Claws",
  "Gift of Competitive Dedication",
  "Gift of Competitive Prosperity",
  "Gift of Competitive Prowess",
  "Gift of Condensed Magic",
  "Gift of Condensed Might",
  "Gift of Dedication",
  "Gift of Dust",
  "Gift of Expertise",
  "Gift of Fangs",
  "Gift of Fortune",
  "Gift of Magic",
  "Gift of Magical Prosperity",
  "Gift of Mastery",
  "Gift of Might",
  "Gift of Mighty Prosperity",
  "Gift of Prosperity",
  "Gift of Prowess",
  "Gift of Scales",
  "Gift of Totems",
  "Gift of Venom",
  "Gift of War Dedication",
  "Gift of War Prosperity",
  "Gift of War Prowess",
  "Mystic Tribute",
])
